[package]
name = "vacation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gltf = "1.0.0"
argh = "0.1.9"
anyhow = "1.0.68"
